export const CHARACTERS_API_FIRST_PAGE = 'https://swapi.co/api/people/?page=1&format=json';

export const CHARACTERS_SET_CURRENT_PAGE    = 'CHARACTERS_SET_CURRENT_PAGE';
export const FETCH_CHARACTERS_LIST_START    = 'FETCH_CHARACTERS_LIST_START';
export const FETCH_CHARACTERS_LIST_SUCCESS  = 'FETCH_CHARACTERS_LIST_SUCCESS';
export const FETCH_CHARACTERS_LIST_ERROR    = 'FETCH_CHARACTERS_LIST_ERROR';