export const PLANETS_API_FIRST_PAGE = 'https://swapi.co/api/planets/?page=1&format=json';

export const PLANETS_SET_CURRENT_PAGE   = 'PLANETS_SET_CURRENT_PAGE';
export const FETCH_PLANETS_LIST_START   = 'FETCH_PLANETS_LIST_START';
export const FETCH_PLANETS_LIST_SUCCESS = 'FETCH_PLANETS_LIST_SUCCESS';
export const FETCH_PLANETS_LIST_ERROR   = 'FETCH_PLANETS_LIST_ERROR';

export const FETCH_PLANET_START   = 'FETCH_PLANET_START';
export const FETCH_PLANET_SUCCESS = 'FETCH_PLANET_SUCCESS';
export const FETCH_PLANET_ERROR   = 'FETCH_PLANET_ERROR';
