export const SPECIES_SET_CURRENT_PAGE  = 'SPECIES_SET_CURRENT_PAGE';
export const FETCH_SPECIES_START       = 'FETCH_SPECIES_START';
export const FETCH_SPECIES_SUCCESS     = 'FETCH_SPECIES_SUCCESS';
export const FETCH_SPECIES_ERROR       = 'FETCH_SPECIES_ERROR';